const fs = require('fs');
let txt = fs.readFileSync('src/prototypes/yanyuan-app-home/index.tsx', 'utf8');

const replacements = [
    [/\{ type: 'input', attributeId: 'user_name', displayName: '用户[\\s\\S]*?\?', info: '显示的用户姓[\\s\\S]*?\?', initialValue: '张明[\\s\\S]*?\?' \},/,
        `{ type: 'input', attributeId: 'user_name', displayName: '用户名', info: '显示的用户姓名', initialValue: '张明远' },`],
    [/\{ type: 'select', attributeId: 'auth_status', displayName: '[\\s\\S]*?认证状\?', info: '用户[\\s\\S]*?认证状\?', initialValue: 'authenticated' \}/,
        `{ type: 'select', attributeId: 'auth_status', displayName: '认证状态', info: '用户认证状态', initialValue: 'authenticated' }`],
    [/\{ name: 'cover_image', desc: '封面\?' \},/,
        `{ name: 'cover_image', desc: '封面图' },`],
    [/var map: Record<string, string> = \{ admin: '李管\?', actor: '张明\?', user: '王观\?' \};/,
        `var map: Record<string, string> = { admin: '李管理', actor: '张明远', user: '王观钰' };`],
    [/var map: Record<string, string> = \{ admin: '[\\s\\S]*?\?', actor: '演员', user: '普通用\?' \};/,
        `var map: Record<string, string> = { admin: '管理员', actor: '演员', user: '普通用户' };`],
    [/\{ id: 'atd-2', title: '认证[\\s\\S]*?申领缴费审核\?笔）'.*?/,
        `{ id: 'atd-2', title: '证书申领缴费审核（3笔）', type: 'review', deadline: '2026-04-05', action_url: '' },`],
    [/\{ id: 'atd-3', title: '红榜推荐审批管理\?项）'.*?/,
        `{ id: 'atd-3', title: '红榜推荐审批管理（5项）', type: 'review', deadline: '2026-04-10', action_url: '' },`],
    [/\{ id: 'atd-4', title: '舆情预警处理\?项）'.*?/,
        `{ id: 'atd-4', title: '舆情预警处理（12项）', type: 'review', deadline: '2026-03-30', action_url: '' }`],
    [/\{ id: 'td-1', title: '演员资格证申领费待缴纳（¥300.00\?'.*?/,
        `{ id: 'td-1', title: '演员资格证申领费待缴纳（¥300.00）', type: 'payment', deadline: '2026-03-31', action_url: '' },`],
    [/\{ id: 'td-2', title: '艺德修养[\\s\\S]*?培训第三期即将开\?'.*?/,
        `{ id: 'td-2', title: '艺德修养培训第三期即将开班', type: 'training', deadline: '2026-04-15', action_url: '' },`],
    [/\{ id: 'td-3', title: '二级演员资格证年审即将到\?'.*?/,
        `{ id: 'td-3', title: '二级演员资格证年审即将到期', type: 'renewal', deadline: '2026-05-01', action_url: '' },`],
    [/\{ id: 'td-4', title: '表演能力[\\s\\S]*?（第二季度）报名\?'.*?/,
        `{ id: 'td-4', title: '表演能力考核（第二季度）报名中', type: 'exam', deadline: '2026-04-20', action_url: '' }`],
    [/\{ id: 'utd-1', title: '您关注的演员 "张明\? 通过资格[\\s\\S]*?认证'.*?/,
        `{ id: 'utd-1', title: '您关注的演员 "张明远" 通过资格认证', type: 'info', deadline: '2026-04-01', action_url: '' },`],
    [/\{ id: 'n-1'.*?/,
        `{ id: 'n-1', title: '关于开展2026年度演员资格认证年审工作的通知', category: '证书发放', publish_time: '2026-03-25', is_read: false },`],
    [/\{ id: 'n-2'.*?/,
        `{ id: 'n-2', title: '第十二届全国优秀演员评选活动报名正式启动', category: '政策公示', publish_time: '2026-03-23', is_read: false },`],
    [/title: '深入[\\s\\S]*?贯彻党的二十大精神，推动演艺事业高质量发\?',/,
        `title: '深入学习贯彻党的二十大精神，推动演艺事业高质量发展',`],
    [/\{ key: 'review', label: '审批管理中心', icon: 'clipboard', color: 'cert', route: '\/prototypes\/yanyuan-app-certification' \},/,
        `{ key: 'review', label: '审批管理中心', icon: 'clipboard', color: 'cert', route: '/prototypes/yanyuan-app-certification' },`],
    [/\{ key: 'auth_review', label: '[\\s\\S]*?认证审核', icon: 'usercheck', color: 'auth', route: '\/prototypes\/yanyuan-app-certification' \},/,
        `{ key: 'auth_review', label: '认证审核', icon: 'usercheck', color: 'auth', route: '/prototypes/yanyuan-app-certification' },`],
    [/\{ key: 'cert_apply', label: '认证[\\s\\S]*?申领'.*?/,
        `{ key: 'cert_apply', label: '证书申领', icon: 'file', color: 'cert', route: '/prototypes/yanyuan-app-cert-apply' },`],
    [/\{ key: 'training', label: '在线[\\s\\S]*?培训'.*?/,
        `{ key: 'training', label: '在线培训', icon: 'book', color: 'train', route: '/prototypes/yanyuan-app-training' },`],
    [/\{ key: 'exam', label: '[\\s\\S]*?预约'.*?/,
        `{ key: 'exam', label: '考核预约', icon: 'clipboard', color: 'exam', route: '/prototypes/yanyuan-app-exam-list' },`],
    [/\{ key: 'auth', label: '个人[\\s\\S]*?认证'.*?/,
        `{ key: 'auth', label: '个人认证', icon: 'shield', color: 'auth', route: '/prototypes/yanyuan-app-certification' },`],
    [/\{ key: 'cert_verify', label: '认证[\\s\\S]*?认证'.*?/,
        `{ key: 'cert_verify', label: '证书验证', icon: 'shield', color: 'cert', route: '/prototypes/yanyuan-app-cert-verify' },`],
    [/\{ key: 'talent_search', label: '人才检\?'.*?/,
        `{ key: 'talent_search', label: '人才检索', icon: 'usercheck', color: 'train', route: '/prototypes/yanyuan-app-profile' },`],
    [/\{ key: 'learning', label: '[\\s\\S]*?中心'.*?/,
        `{ key: 'learning', label: '学习中心', icon: 'book', color: 'exam', route: '/prototypes/yanyuan-app-training' },`],
    [/\{ key: 'honor', label: '红黑\?'.*?/,
        `{ key: 'honor', label: '红黑榜', icon: 'chart', color: 'auth', route: '/prototypes/yanyuan-app-profile' }`],
    [/\* - Admin：显示审批管理管理考核相关快捷入口（审批管理中心、认证审核、数据统计、系统设置）\?/,
        `* - Admin：显示审批管理相关快捷入口（审批中心、认证审核、数据统计、系统设置）`],
    [/\*          底部Tab[\\s\\S]*?"替代"认证[\\s\\S]*?"，待办为审核类待\?/,
        `*          底部Tab"管理"替代"认证"，待办为审核类待办`],
    [/\* - Actor：显示证[\\s\\S]*?培训\/[\\s\\S]*?考核相关快捷入口，底部标\?Tab，待办为缴费\/[\\s\\S]*?培训\/[\\s\\S]*?\?/,
        `* - Actor：显示证书/培训/考核相关快捷入口，底部标准Tab，待办为缴费/培训/考核类`],
    [/\* - User：显示浏览查询类快捷入口（证书验证、人才检\?.*?学习中心、红黑榜），/,
        `* - User：显示浏览查询类快捷入口（证书验证、人才检索、学习中心、红黑榜），`],
    [/\*          底部Tab隐藏"[\\s\\S]*?认证"Tab，待办较\?/,
        `*          底部Tab隐藏"认证"Tab，待办较少`],
    [/payment: '[\\s\\S]*?', training: '[\\s\\S]*?培训', exam: '[\\s\\S]*?', renewal: '[\\s\\S]*?', review: '[\\s\\S]*?', info: '通知'/,
        `payment: '待缴费', training: '培训', exam: '考核', renewal: '年审', review: '待审核', info: '通知'`],
    [/authenticated: '[\\s\\S]*?认证', pending: '[\\s\\S]*?', rejected: '[\\s\\S]*?', none: 'δ[\\s\\S]*?认证'/,
        `authenticated: '已认证', pending: '审核中', rejected: '已驳回', none: '未认证'`],
    [/return map\[status\] \|\| 'δ[\\s\\S]*?认证';/,
        `return map[status] || '未认证';`],
    [/if \(diff < 0\) return '已过\?';/,
        `if (diff < 0) return '已过期';`],
    [/if \(diff <= 7\) return '剩余 ' \+ diff \+ ' \?';/,
        `if (diff <= 7) return '剩余 ' + diff + ' 天';`],
    [/console\.warn\('未知的动\?', name\);/,
        `console.warn('未知的动作', name);`],
    [/\{userName\}，欢迎回\?/,
        `{userName}，欢迎回来`],
    [/\{getRoleLabel\(currentRole\)\} \?/,
        `{getRoleLabel(currentRole)} ▾`],
    [/<div className="yanyuan-home-auth-guide-title">完成个人[\\s\\S]*?认证，解锁更多功\?<\/div>/,
        `<div className="yanyuan-home-auth-guide-title">完成个人认证，解锁更多功能</div>`],
    [/<div className="yanyuan-home-auth-guide-desc">[\\s\\S]*?认证后可使用认证[\\s\\S]*?认证、在线学习、个人中心等全部功能<\/div>/,
        `<div className="yanyuan-home-auth-guide-desc">认证后可使用证书验证、在线学习、个人中心等全部功能</div>`],
    [/立即[\\s\\S]*?认证/, `立即认证`],
    [/<div className="yanyuan-home-auth-modal-title">请先完成个人[\\s\\S]*?认证<\/div>/,
        `<div className="yanyuan-home-auth-modal-title">请先完成个人认证</div>`],
    [/<div className="yanyuan-home-auth-modal-desc">完成个人信息[\\s\\S]*?认证后，即可使用平台全部功能<\/div>/,
        `<div className="yanyuan-home-auth-modal-desc">完成个人信息认证后，即可使用平台全部功能</div>`],
    [/<button className="yanyuan-home-auth-modal-btn primary" onClick=\{function \(\) \{ navigateTo\('\/prototypes\/yanyuan-app-info-fill'\); \}\}>去认\?<\/button>/,
        `<button className="yanyuan-home-auth-modal-btn primary" onClick={function () { navigateTo('/prototypes/yanyuan-app-info-fill'); }}>去认证</button>`],
    [/<span className="yanyuan-home-detail-sheet-close" onClick=\{function \(\) \{ setSelectedTodo\(null\); \}\}>\?<\/span>/,
        `<span className="yanyuan-home-detail-sheet-close" onClick={function () { setSelectedTodo(null); }}>✕</span>`],
    [/\{selectedTodo\.description \|\| '请点击下方按钮前往处理该待办事项，逾期未处理可能影响您的相关业务进度\?'\}/,
        `{selectedTodo.description || '请点击下方按钮前往处理该待办事项，逾期未处理可能影响您的相关业务进度。'}`],
    [/\{currentRole === 'admin' \? '去审\?' : currentRole === 'user' \? '查看详情' : '去处\?'\}/,
        `{currentRole === 'admin' ? '去审批' : currentRole === 'user' ? '查看详情' : '去处理'}`],
    [/<p>\{selectedNotice\.title\}。请相关人员及时关注并按要求完成相应事项\?<\/p>/,
        `<p>{selectedNotice.title}。请相关人员及时关注并按要求完成相应事项。</p>`],
    [/<p>一、请各相关人员在规定时间内完成所需操作，逾期将按相关规定处理\?<\/p>/,
        `<p>一、请各相关人员在规定时间内完成所需操作，逾期将按相关规定处理。</p>`],
    [/<p>二、如有疑问，请联系平台客服或相关[\\s\\S]*?部门\?<\/p>/,
        `<p>二、如有疑问，请联系平台客服或相关管理部门。</p>`],
    [/<p>三、本通知自发布之日起生效\?<\/p>/,
        `<p>三、本通知自发布之日起生效。</p>`],
    [/<p style=\{\{ marginTop: 24, color: '#8E8E93', fontSize: 13 \}\}>中国演艺人才[\\s\\S]*?与服务平\?<\/p>/,
        `<p style={{ marginTop: 24, color: '#8E8E93', fontSize: 13 }}>中国演艺人才管理与服务平台</p>`],
    [/<p>在新时代中国特色社会主义思想指引下，演艺行业积极践行社会主义核心价值观，大力弘扬民族优秀传统文化。本文深入解读新时代演艺人才培养的重要方针政策，为广大从业者提供学习指导\?<\/p>/,
        `<p>在新时代中国特色社会主义思想指引下，演艺行业积极践行社会主义核心价值观，大力弘扬民族优秀传统文化。本文深入解读新时代演艺人才培养的重要方针政策，为广大从业者提供学习指导。</p>`],
    [/<p>广大演艺工作者要始终坚持以人民为中心的创作导向，深入生活、扎根人民，创作出更多无愧于时代的优秀作品\?<\/p>/,
        `<p>广大演艺工作者要始终坚持以人民为中心的创作导向，深入生活、扎根人民，创作出更多无愧于时代的优秀作品。</p>`],
    [/<p>演艺人才应自觉遵守法律法规，恪守职业道德，做到德艺双馨，为社会传递正能量\?<\/p>/,
        `<p>演艺人才应自觉遵守法律法规，恪守职业道德，做到德艺双馨，为社会传递正能量。</p>`],
    [/<p>通过系统化的[\\s\\S]*?培训体系和科学的评价机制，不断提升演艺人才的专业素养和综合能力\?<\/p>/,
        `<p>通过系统化的培训体系和科学的评价机制，不断提升演艺人才的专业素养和综合能力。</p>`],
    [/<span style=\{\{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' \}\}>待处\?<\/span>/,
        `<span style={{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' }}>待处理</span>`],
    [/<span style=\{\{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' \}\}>已处\?<\/span>/,
        `<span style={{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' }}>已处理</span>`],
    [/<span style=\{\{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' \}\}>认证[\\s\\S]*?发放<\/span>/,
        `<span style={{ fontSize: 14, color: '#8E8E93', paddingBottom: 4, whiteSpace: 'nowrap' }}>证书发放</span>`],
    [/var TAB_LIST_BY_ROLE: Record<string, Array<\{ label: string; icon: string \}>> = \{\n  admin: \[\n    \{ label: '首页', icon: 'home' \},\n    \{ label: '[\\s\\S]*?Ƶ', icon: 'video' \},\n    \{ label: '[\\s\\S]*?', icon: 'settings' \},\n    \{ label: '认证[\\s\\S]*?', icon: 'award' \},\n    \{ label: '[\\s\\S]*?', icon: 'book' \},\n    \{ label: '[\\s\\S]*?', icon: 'user' \}\n  \],\n  actor: \[\n    \{ label: '首页', icon: 'home' \},\n    \{ label: '[\\s\\S]*?Ƶ', icon: 'video' \},\n    \{ label: '[\\s\\S]*?认证', icon: 'shield' \},\n    \{ label: '认证[\\s\\S]*?', icon: 'award' \},\n    \{ label: '[\\s\\S]*?', icon: 'book' \},\n    \{ label: '[\\s\\S]*?', icon: 'user' \}\n  \],\n  user: \[\n    \{ label: '首页', icon: 'home' \},\n    \{ label: '[\\s\\S]*?Ƶ', icon: 'video' \},\n    \{ label: '[\\s\\S]*?认证', icon: 'shield' \},\n    \{ label: '[\\s\\S]*?', icon: 'book' \},\n    \{ label: '[\\s\\S]*?', icon: 'user' \}\n  \]\n\};/g,
        `var TAB_LIST_BY_ROLE: Record<string, Array<{ label: string; icon: string }>> = {
  admin: [
    { label: '首页', icon: 'home' },
    { label: '短视频', icon: 'video' },
    { label: '管理', icon: 'settings' },
    { label: '证书', icon: 'award' },
    { label: '学习', icon: 'book' },
    { label: '我的', icon: 'user' }
  ],
  actor: [
    { label: '首页', icon: 'home' },
    { label: '短视频', icon: 'video' },
    { label: '认证', icon: 'shield' },
    { label: '证书', icon: 'award' },
    { label: '学习', icon: 'book' },
    { label: '我的', icon: 'user' }
  ],
  user: [
    { label: '首页', icon: 'home' },
    { label: '短视频', icon: 'video' },
    { label: '验证', icon: 'shield' },
    { label: '学习', icon: 'book' },
    { label: '我的', icon: 'user' }
  ]
};`]
];

for (const [search, repl] of replacements) {
    if (!txt.match(search)) {
        console.log("No match found for: " + search);
    }
    txt = txt.replace(search, repl);
}
fs.writeFileSync('src/prototypes/yanyuan-app-home/index.tsx', txt);
console.log('Rewrite done');
